stages:
  - build
  - test

variables:
  TAG: $CI_BUILD_REF
  IMAGE: $CI_REGISTRY_IMAGE

services:
  - docker:dind

image: docker

before_script:
  - apk add --update py-pip
  - pip install docker-compose
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose -f docker-compose.common-python.yml -f docker-compose.prod-python.yml build
    - docker-compose -f docker-compose.common-python.yml -f docker-compose.prod-python.yml push

test-python:
  stage: test
  script:
    - docker-compose -f docker-compose.common-python.yml -f docker-compose.prod-python.yml pull python
    - docker-compose -f docker-compose.common-python.yml -f docker-compose.prod-python.yml run --rm --entrypoint pytest python